name: Build and Deploy

on: [push, pull_request]

jobs:
  # test-frontend:
    # name: Frontend Testing
    # runs-on: ubuntu-latest
    # steps:
    # - uses: actions/checkout@v2
    # - name: Install dependencies
    #  run: (cd frontend && npm ci)
    # - name: Run tests
    #  run: (cd frontend && npm run test:unit)
        
  lint:
    name: Lint & fix files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: (cd frontend && npm ci)
    - name: Lint files
      run: (cd frontend && npm run lint)
        
        
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: (cd frontend && npm ci)
    - name: Build app
      run: (cd frontend && npm run build)
